vacay_destination = ['Chicago', 'New York', 'Miami']
chi_restaurants = ['Giordanos', 'Leonas', 'The Purple Pig']
ny_restaurants = ['Gramercy Tavern', 'La Grande Boucherie', 'Raouls']
mi_restaurants = ['Red Rooster', 'Cvi.che 105', 'Mignonette Downtown']
transportation = ['Car', 'Train', 'Plane']
entertainment = ['A play', 'A concert', 'Netflix and chill']